export type MarketRegion = 'US' | 'IN' | 'EU' | 'UK' | 'JP' | 'AU' | 'CA' | 'HK';

export interface MarketConfig {
  id: MarketRegion;
  name: string;
  flag: string;
  currency: string;
  currencySymbol: string;
  locale: string;
  exchangeName: string;
  exchangeCode: string;
  marketHours: { open: string; close: string; timezone: string };
  indices: { symbol: string; name: string; displaySymbol: string }[];
  popularStocks: { symbol: string; name: string; sector: string }[];
  symbolSuffix: string; // e.g., ".NS" for NSE, ".L" for London
}

export const MARKETS: Record<MarketRegion, MarketConfig> = {
  US: {
    id: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    exchangeName: 'NYSE / NASDAQ',
    exchangeCode: 'US',
    marketHours: { open: '09:30', close: '16:00', timezone: 'America/New_York' },
    symbolSuffix: '',
    indices: [
      { symbol: '^GSPC', name: 'S&P 500', displaySymbol: 'SPX' },
      { symbol: '^IXIC', name: 'NASDAQ', displaySymbol: 'NDX' },
      { symbol: '^DJI', name: 'Dow Jones', displaySymbol: 'DJI' },
      { symbol: '^RUT', name: 'Russell 2000', displaySymbol: 'RUT' },
    ],
    popularStocks: [
      { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology' },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon.com', sector: 'Consumer' },
      { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Automotive' },
      { symbol: 'META', name: 'Meta Platforms', sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology' },
      { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance' },
      { symbol: 'V', name: 'Visa Inc.', sector: 'Finance' },
      { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
      { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer' },
      { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
      { symbol: 'DIS', name: 'Walt Disney', sector: 'Communication' },
      { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication' },
      { symbol: 'AMD', name: 'AMD Inc.', sector: 'Technology' },
      { symbol: 'INTC', name: 'Intel Corp.', sector: 'Technology' },
      { symbol: 'BA', name: 'Boeing Co.', sector: 'Industrial' },
      { symbol: 'KO', name: 'Coca-Cola Co.', sector: 'Consumer' },
      { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
      { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
    ],
  },

  IN: {
    id: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    locale: 'en-IN',
    exchangeName: 'NSE / BSE',
    exchangeCode: 'NSE',
    marketHours: { open: '09:15', close: '15:30', timezone: 'Asia/Kolkata' },
    symbolSuffix: '.NS',
    indices: [
      { symbol: '^NSEI', name: 'NIFTY 50', displaySymbol: 'NIFTY' },
      { symbol: '^BSESN', name: 'SENSEX', displaySymbol: 'SENSEX' },
      { symbol: '^NSEBANK', name: 'BANK NIFTY', displaySymbol: 'BANKNIFTY' },
      { symbol: '^CNXIT', name: 'NIFTY IT', displaySymbol: 'NIFTYIT' },
    ],
    popularStocks: [
      { symbol: 'RELIANCE.NS', name: 'Reliance Industries', sector: 'Energy' },
      { symbol: 'TCS.NS', name: 'Tata Consultancy Services', sector: 'Technology' },
      { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Finance' },
      { symbol: 'INFY.NS', name: 'Infosys Ltd.', sector: 'Technology' },
      { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Finance' },
      { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', sector: 'Consumer' },
      { symbol: 'SBIN.NS', name: 'State Bank of India', sector: 'Finance' },
      { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Communication' },
      { symbol: 'ITC.NS', name: 'ITC Ltd.', sector: 'Consumer' },
      { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Finance' },
      { symbol: 'LT.NS', name: 'Larsen & Toubro', sector: 'Industrial' },
      { symbol: 'AXISBANK.NS', name: 'Axis Bank', sector: 'Finance' },
      { symbol: 'WIPRO.NS', name: 'Wipro Ltd.', sector: 'Technology' },
      { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', sector: 'Consumer' },
      { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', sector: 'Automotive' },
      { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Automotive' },
      { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma', sector: 'Healthcare' },
      { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Materials' },
      { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', sector: 'Utilities' },
      { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', sector: 'Industrial' },
    ],
  },

  EU: {
    id: 'EU',
    name: 'Europe',
    flag: '🇪🇺',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'de-DE',
    exchangeName: 'XETRA / Euronext',
    exchangeCode: 'XETRA',
    marketHours: { open: '09:00', close: '17:30', timezone: 'Europe/Berlin' },
    symbolSuffix: '.DE',
    indices: [
      { symbol: '^GDAXI', name: 'DAX 40', displaySymbol: 'DAX' },
      { symbol: '^FCHI', name: 'CAC 40', displaySymbol: 'CAC40' },
      { symbol: '^STOXX50E', name: 'Euro Stoxx 50', displaySymbol: 'STOXX50' },
      { symbol: '^AEX', name: 'AEX Amsterdam', displaySymbol: 'AEX' },
    ],
    popularStocks: [
      { symbol: 'SAP.DE', name: 'SAP SE', sector: 'Technology' },
      { symbol: 'SIE.DE', name: 'Siemens AG', sector: 'Industrial' },
      { symbol: 'ALV.DE', name: 'Allianz SE', sector: 'Finance' },
      { symbol: 'BAS.DE', name: 'BASF SE', sector: 'Materials' },
      { symbol: 'DTE.DE', name: 'Deutsche Telekom', sector: 'Communication' },
      { symbol: 'BMW.DE', name: 'BMW AG', sector: 'Automotive' },
      { symbol: 'ADS.DE', name: 'Adidas AG', sector: 'Consumer' },
      { symbol: 'MUV2.DE', name: 'Munich Re', sector: 'Finance' },
      { symbol: 'VOW3.DE', name: 'Volkswagen AG', sector: 'Automotive' },
      { symbol: 'DBK.DE', name: 'Deutsche Bank', sector: 'Finance' },
      { symbol: 'ASML.AS', name: 'ASML Holdings', sector: 'Technology' },
      { symbol: 'MC.PA', name: 'LVMH', sector: 'Consumer' },
      { symbol: 'OR.PA', name: "L'Oreal", sector: 'Consumer' },
      { symbol: 'AI.PA', name: 'Air Liquide', sector: 'Materials' },
      { symbol: 'SAN.PA', name: 'Sanofi', sector: 'Healthcare' },
      { symbol: 'BNP.PA', name: 'BNP Paribas', sector: 'Finance' },
      { symbol: 'TTE.PA', name: 'TotalEnergies', sector: 'Energy' },
      { symbol: 'AIR.PA', name: 'Airbus SE', sector: 'Industrial' },
      { symbol: 'PHIA.AS', name: 'Philips NV', sector: 'Healthcare' },
      { symbol: 'INGA.AS', name: 'ING Group', sector: 'Finance' },
    ],
  },

  UK: {
    id: 'UK',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    exchangeName: 'London Stock Exchange',
    exchangeCode: 'LSE',
    marketHours: { open: '08:00', close: '16:30', timezone: 'Europe/London' },
    symbolSuffix: '.L',
    indices: [
      { symbol: '^FTSE', name: 'FTSE 100', displaySymbol: 'FTSE100' },
      { symbol: '^FTMC', name: 'FTSE 250', displaySymbol: 'FTSE250' },
    ],
    popularStocks: [
      { symbol: 'SHEL.L', name: 'Shell PLC', sector: 'Energy' },
      { symbol: 'AZN.L', name: 'AstraZeneca', sector: 'Healthcare' },
      { symbol: 'HSBA.L', name: 'HSBC Holdings', sector: 'Finance' },
      { symbol: 'ULVR.L', name: 'Unilever PLC', sector: 'Consumer' },
      { symbol: 'BP.L', name: 'BP PLC', sector: 'Energy' },
      { symbol: 'GSK.L', name: 'GSK PLC', sector: 'Healthcare' },
      { symbol: 'RIO.L', name: 'Rio Tinto', sector: 'Materials' },
      { symbol: 'DGE.L', name: 'Diageo PLC', sector: 'Consumer' },
      { symbol: 'LLOY.L', name: 'Lloyds Banking', sector: 'Finance' },
      { symbol: 'BARC.L', name: 'Barclays PLC', sector: 'Finance' },
      { symbol: 'VOD.L', name: 'Vodafone Group', sector: 'Communication' },
      { symbol: 'BATS.L', name: 'British American Tobacco', sector: 'Consumer' },
      { symbol: 'NG.L', name: 'National Grid', sector: 'Utilities' },
      { symbol: 'RR.L', name: 'Rolls-Royce', sector: 'Industrial' },
      { symbol: 'GLEN.L', name: 'Glencore PLC', sector: 'Materials' },
    ],
  },

  JP: {
    id: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    locale: 'ja-JP',
    exchangeName: 'Tokyo Stock Exchange',
    exchangeCode: 'TSE',
    marketHours: { open: '09:00', close: '15:00', timezone: 'Asia/Tokyo' },
    symbolSuffix: '.T',
    indices: [
      { symbol: '^N225', name: 'Nikkei 225', displaySymbol: 'NIKKEI' },
      { symbol: '^TOPX', name: 'TOPIX', displaySymbol: 'TOPIX' },
    ],
    popularStocks: [
      { symbol: '7203.T', name: 'Toyota Motor', sector: 'Automotive' },
      { symbol: '6758.T', name: 'Sony Group', sector: 'Technology' },
      { symbol: '6861.T', name: 'Keyence Corp', sector: 'Technology' },
      { symbol: '8306.T', name: 'Mitsubishi UFJ', sector: 'Finance' },
      { symbol: '9984.T', name: 'SoftBank Group', sector: 'Technology' },
      { symbol: '6902.T', name: 'Denso Corp', sector: 'Automotive' },
      { symbol: '7267.T', name: 'Honda Motor', sector: 'Automotive' },
      { symbol: '9432.T', name: 'NTT Corp', sector: 'Communication' },
      { symbol: '6501.T', name: 'Hitachi Ltd', sector: 'Industrial' },
      { symbol: '4502.T', name: 'Takeda Pharma', sector: 'Healthcare' },
    ],
  },

  AU: {
    id: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencySymbol: 'A$',
    locale: 'en-AU',
    exchangeName: 'ASX',
    exchangeCode: 'ASX',
    marketHours: { open: '10:00', close: '16:00', timezone: 'Australia/Sydney' },
    symbolSuffix: '.AX',
    indices: [
      { symbol: '^AXJO', name: 'ASX 200', displaySymbol: 'ASX200' },
    ],
    popularStocks: [
      { symbol: 'BHP.AX', name: 'BHP Group', sector: 'Materials' },
      { symbol: 'CBA.AX', name: 'Commonwealth Bank', sector: 'Finance' },
      { symbol: 'CSL.AX', name: 'CSL Ltd', sector: 'Healthcare' },
      { symbol: 'NAB.AX', name: 'National Australia Bank', sector: 'Finance' },
      { symbol: 'WBC.AX', name: 'Westpac Banking', sector: 'Finance' },
      { symbol: 'ANZ.AX', name: 'ANZ Group', sector: 'Finance' },
      { symbol: 'WES.AX', name: 'Wesfarmers', sector: 'Consumer' },
      { symbol: 'MQG.AX', name: 'Macquarie Group', sector: 'Finance' },
      { symbol: 'FMG.AX', name: 'Fortescue Metals', sector: 'Materials' },
      { symbol: 'TLS.AX', name: 'Telstra Corp', sector: 'Communication' },
    ],
  },

  CA: {
    id: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'C$',
    locale: 'en-CA',
    exchangeName: 'TSX',
    exchangeCode: 'TSX',
    marketHours: { open: '09:30', close: '16:00', timezone: 'America/Toronto' },
    symbolSuffix: '.TO',
    indices: [
      { symbol: '^GSPTSE', name: 'S&P/TSX', displaySymbol: 'TSX' },
    ],
    popularStocks: [
      { symbol: 'RY.TO', name: 'Royal Bank of Canada', sector: 'Finance' },
      { symbol: 'TD.TO', name: 'Toronto-Dominion Bank', sector: 'Finance' },
      { symbol: 'SHOP.TO', name: 'Shopify Inc.', sector: 'Technology' },
      { symbol: 'ENB.TO', name: 'Enbridge Inc.', sector: 'Energy' },
      { symbol: 'CNR.TO', name: 'Canadian National Railway', sector: 'Industrial' },
      { symbol: 'BNS.TO', name: 'Bank of Nova Scotia', sector: 'Finance' },
      { symbol: 'CP.TO', name: 'Canadian Pacific', sector: 'Industrial' },
      { symbol: 'BMO.TO', name: 'Bank of Montreal', sector: 'Finance' },
      { symbol: 'SU.TO', name: 'Suncor Energy', sector: 'Energy' },
      { symbol: 'BCE.TO', name: 'BCE Inc.', sector: 'Communication' },
    ],
  },

  HK: {
    id: 'HK',
    name: 'Hong Kong',
    flag: '🇭🇰',
    currency: 'HKD',
    currencySymbol: 'HK$',
    locale: 'zh-HK',
    exchangeName: 'HKEX',
    exchangeCode: 'HKEX',
    marketHours: { open: '09:30', close: '16:00', timezone: 'Asia/Hong_Kong' },
    symbolSuffix: '.HK',
    indices: [
      { symbol: '^HSI', name: 'Hang Seng Index', displaySymbol: 'HSI' },
    ],
    popularStocks: [
      { symbol: '0700.HK', name: 'Tencent Holdings', sector: 'Technology' },
      { symbol: '9988.HK', name: 'Alibaba Group', sector: 'Technology' },
      { symbol: '0005.HK', name: 'HSBC Holdings', sector: 'Finance' },
      { symbol: '1299.HK', name: 'AIA Group', sector: 'Finance' },
      { symbol: '3690.HK', name: 'Meituan', sector: 'Technology' },
      { symbol: '0941.HK', name: 'China Mobile', sector: 'Communication' },
      { symbol: '2318.HK', name: 'Ping An Insurance', sector: 'Finance' },
      { symbol: '9618.HK', name: 'JD.com', sector: 'Consumer' },
      { symbol: '1810.HK', name: 'Xiaomi Corp', sector: 'Technology' },
      { symbol: '9888.HK', name: 'Baidu Inc.', sector: 'Technology' },
    ],
  },
};
